### ISSUE TITLE
SQL Explorer can't insert exported config.

### ISSUE THREAD

**Issue by abrougher** [JumpMind/metl#104]
Example of valid SQL that will not work using the sql explorer. 

insert into METL_PROJECT (ID, NAME, DESCRIPTION, DELETED, CREATE_TIME, CREATE_BY, LAST_UPDATE_BY, LAST_UPDATE_TIME) values ('c800e608-6de2-4592-8e21-df92b985253c','PCA Integrations','PCA Integrations',0,{ts '2015-04-14 11:36:14.618'},null,null,{ts '2015-04-14 11:36:22.251'});

**Comment by chenson42** [comment]
Are you sure about this?  It ran just fine for me.

**Comment by abrougher** [comment]
I still get the same error when trying to run from the Explorer window.


SQL Message: 
Syntax error in SQL statement "INSERT INTO METL_PROJECT (ID, NAME, DESCRIPTION, DELETED, CREATE_TIME, CREATE_BY,
LAST_UPDATE_BY, LAST_UPDATE_TIME) VALUES ('c800e608-6de2-4592-8e21-df92b985253c','PCA Integrations','PCA
Integrations',0, TS '2015-04-14 11:36:14.618' ,NULL,NULL [*]"; expected "[, ::, *, /, %, +, -, ||, ~, !~, NOT, LIKE,
REGEXP, IS, IN, BETWEEN, AND, OR, ,, )"; SQL statement:

insert into METL_PROJECT (ID, NAME, DESCRIPTION, DELETED, CREATE_TIME, CREATE_BY, LAST_UPDATE_BY, LAST_UPDATE_TIME)
values ('c800e608-6de2-4592-8e21-df92b985253c','PCA Integrations','PCA Integrations',0, ts '2015-04-14 11:36:14.618'
,null,null [42001-190]

SQL State: 42001
Error Code: 42001

**Comment by chenson42** [comment]
This is a corrupt database issue
