### ISSUE TITLE
Bottom of the run screen scrolls to the far right when click any row.

### ISSUE THREAD

**Issue by abrougher** [JumpMind/metl#151]
The bottom of the run screen contains log output. If one row of the log output contains a very long output message, clicking on any row in the table causes the scroll bar to slide to the far right. Most rows aren't this long so the user must scroll back to the left to see the log message.

**Comment by chenson42** [comment]
I can't recreate this with the latest version.  I think it might be fixed by the swap out of Grid for Table

**Comment by abrougher** [comment]
As I click up and down the log records (bottom table) it scrolls to the far left, then the right, and repeats.

**Comment by chenson42** [comment]
I think that might be because you are scrolling down with focus on that "cell".  Put focus on the left most cell and scroll down.

**Comment by abrougher** [comment]
Bingo. Thanks.
