### ISSUE TITLE
Labels cannot be copied and pasted.

### ISSUE THREAD

**Issue by abrougher** [JumpMind/metl#160]
A lot of table rows have details I'd like to copy and paste.

An example is searching model attributes for a column with 'kitchen' in the name. The result is displayed and is 100 characters in length. I'd like to copy this column name instead of retyping it. When  I try to select the attribute name I can highlight it but the Vaadin component removes the highlight and selects the row.

This is true for most tables.

Chrome Browser: Version 47.0.2526.73 m

**Comment by chenson42** [comment]
This is because of this style in _apptheme.css. 

    .v-table-body, .v-grid {
    -webkit-touch-callout: none;
    -webkit-user-select: none;
    -khtml-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
     user-select: none;
   }

I added it intentionally because I didn't like accidentally selecting something.  I'll remove it for a few releases and we'll see what people think :-)
