### ISSUE TITLE
DataDiff component fails on lower case table names

### ISSUE THREAD

**Issue by gwilmer** [JumpMind/metl#170]
DataDiff is having problems with case sensitivity in table names.  If your model table name is lower case and your database table names are lower case, when data diff constructs the sql statement to compare, it is using upper case table names and the select is failing.  I'm guessing we are quoting the table names in creation which is causing them to be case sensitive?

**Comment by gwilmer** [comment]
DataDiff uses H2 for database compare.  Tables are quoted which in H2 means they are case sensitive.  If the model case doesn't match the table creation case this is when we have troubles.

**Comment by chenson42** [comment]
I think line 327 needs to pass in false for the third arg to force the tables to be created with out quotes
