### ISSUE TITLE
Display the logged in user's name on Logout button.

### ISSUE THREAD

**Issue by abrougher** [JumpMind/metl#171]
...or another means to see what user is currently logged in. 

This is important because the design deployment can be different for different users.

**Comment by chenson42** [comment]
The logged in user's name is to the left of the logout button already.

**Comment by abrougher** [comment]
My mistake. I was logged in as 'admin' and assumed the the button to the left was an Administrative button.

**Comment by buildJumpMind** [comment]
Yeah.  I changed the default user from admin to default user because of that. ;-)
