### ISSUE TITLE
UI removes DataDiff component settings after placed in a flow

### ISSUE THREAD

**Issue by nrichardson99** [JumpMind/metl#250]
To recreate add a DataDiff component to a flow, note the settings of Source of Old Version and Source of New Version.  Next click another component then click back on the DataDiff component.  These two settings have been removed from the list and Input Model is added.

**Comment by abrougher** [comment]
Are the settings blank or is the field gone?

**Comment by nrichardson99** [comment]
fields are gone from UI screen.
