### ISSUE TITLE
Execution steps are not being updated consistently on the run screen.

### ISSUE THREAD

**Issue by abrougher** [JumpMind/metl#255]
If we have two steps, the first step messages sent should be similar to the second steps messages received. This is often not the case because the second step values are not being updated in the UI.

**Comment by abrougher** [comment]
@chenson42 can you please review this change. We were pre-saving the execution step in the before handle method. This save updated the lastUpdateTimestamp for the step. When the received messages count got incremented on step 2, the time difference between last update and the current time did not exceed the 500 ms we wait before refreshing the UI. In some situations, the secondary component was never updated until the first component finished.

**Comment by chenson42** [comment]
The before was so if you have a long running handle you record that you received a message (i think)

**Comment by abrougher** [comment]
@chenson42, that makes sense. I put the save back in the pre-handle. I created a new map in the tracker class to save the last time the stats were updated for each step.
