### ISSUE TITLE
Provide ability to utlitize Flow Variables globally

### ISSUE THREAD

**Issue by nrichardson99** [JumpMind/metl#257]
Since Flow Parameters are immutable, would be nice to provide a way to create, use and update global variables within a flow.

**Comment by gwilmer** [comment]
This keeps coming up in complex flows.  I have a flow now that would benefit greatly from having the ability to set or stamp flow variables that can be used by other components (specifically a bearer token that needs to be used by several web service callers throughout a flow).  In a simple flow, it isn't bad to simply pass the variable along in message headers from component to component.  However, there are still components that don't pass along message headers (like Temp RDBMS component) as they receive many messages inbound and create a completely different set of messages outbound.  The passing along of message headers in these situations becomes confusing, and not sure it's the right thing to do.  

I think we need to be able to have all component runtimes have the ability to read/write from a set of global flow variables.  They would need to be synchronized as threading would def. be an issue.  I think we should be able to:

 - read / write from these variables in the script component
 - possibly allow the stamp component to write to these variables (i.e. select whether you want to stamp something in the message header or in the flow variables)
 - allow all components variable substitution to utilize these flow variables.  (this would make something like a bearer token used by multiple web service callers very simple as we could use flow variables in the http header).

**Comment by gwilmer** [comment]
ComponentContext now has access to a synchronized map in FlowRuntime called flowVariables.  flowParameters are still immutable.  flowVariables can be set and read by different components in the flow.  From script component:

context.flowVariables.put(key,value) and
context.flowVariables.get(key)

Will update stamp component in a different issue.
