### ISSUE TITLE
Add support for exposing flows as web services that both inject and return flow generated content

### ISSUE THREAD

**Issue by chenson42** [JumpMind/metl#275]
Add support for exposing flows as web services that both inject and return flow generated content.

My plan is to do that following:
- Add new HttpRequest and Response components
- Add new IComponentDeploymentListener interface that can be configured in components.xml
  - onDeploy
  - onUndeploy
- The HttpRequest onEnable will register with a new IRequestRegistry spring bean.  onDisable it will unregister.
- ExecutionApi (or a new Servlet) will ask the IRequestRegistry for a match to it's URL / HttpMethod.  The best match will return a request object that can be invoked by the ExecutionApi. 
- Each invocation will be an independent execution of a flow.

**Comment by gwilmer** [comment]
So we are talking REST based services only at this point right?  How will the user define what the web request and web response looks like?  I.E. it would be nice for the request and response to have .xsd's so those can be delivered to whoever is calling the rest service such that they have a contract for what input and output looks like.  So, what goes into  defining what the request looks like.  There is really a model aspect (i.e. here are the entities and attributes that get passed in) as well as a format (i.e. here is how that model is translated into either json format or xml format).  So will the request be defined by model and format, or will it be a template like in the xmlformatter and parser?   If we go that route, what does the template look like for json and will we be able to generate an xsd from it?

**Comment by abrougher** [comment]
Is this complete?

**Comment by chenson42** [comment]
This is complete
