### ISSUE TITLE
Output Model Getting Set on Text File Reader

### ISSUE THREAD

**Issue by gwilmer** [JumpMind/metl#289]
I had a model that I was unable to delete from the UI.  The UI stated that the model was still in use, and I couldn't find where it was being used.  I ended up querying the database to see which component had it set, and it ended up being used on a Text File Reader (which doesn't have an output model and it shouldn't be able to be set.)  Not sure how it got there, but it did.  Guessing it is some UI bug where we automatically try to set the input/output model.  Need to track this one down.

**Comment by chenson42** [comment]
Maybe the components.xml changed to disallow it.  Closing this until we can duplicate.
