### ISSUE TITLE
'Transformer now passes cntrl msgs through' update breaks downstream components not expecting them.

### ISSUE THREAD

**Issue by nrichardson99** [JumpMind/metl#330]
We have a flow that has two transformers flowing into one.  Since the second transformer sends on each control message downstream this causes other components to execute certain steps prematurely.  For instance we have a text writer after this that as the data is being written to the text file it appears to close the connection and recreate the file when the second set of data arrives so we lose part of the data in the file.  The source data pulls take different amounts of time so there is a time lag between the control messages.  Our work around was to add a merge prior to the last transformer.

**Comment by chenson42** [comment]
This bit @abrougher.  Really needs to be addressed.

**Comment by abrougher** [comment]
Yeah this one can be confusing. I had two DBReaders feeding a transformer which resulted in extra control messages and some strange behavior on a file writer.
