### ISSUE TITLE
Temp RDBMS Component: Allow indexes to be created.

### ISSUE THREAD

**Issue by abrougher** [JumpMind/metl#333]
Two options:

1) Create a configurable screen where a user can check columns they want indexed.

2) Create an init script that is run during the initialization of the db.

The work around for now is to create a special model and mark the fields we want indexed as a PK.

**Comment by philipmarzullo64** [comment]
I prefer the option of creating an init script that is run during initialization of the db. This provides the most flexibility.

**Comment by philipmarzullo64** [comment]
[metlcodechange.zip](https://github.com/JumpMind/metl/files/1270996/metlcodechange.zip)
I attached code to implement this functionality. Can you merge these code changes in (if it is correct) into the latest release?

**Comment by abrougher** [comment]
@gwilmer, I've reviewed and tested the code. All looks good.
