### ISSUE TITLE
Transformer Component not forwarding new model attributes.

### ISSUE THREAD

**Issue by abrougher** [JumpMind/metl#371]
The transformer component will not forward new model attributes without opening the component and closing it again. My guess is that the model attribute setting must exist on the component before it will get forwarded, regardless of it having a transform or not. 

This can be confusing for users. 

This should be fixed to forward on attribute values in the model even if the model attribute transform setting cannot be found.

The work around is to open the component and close it so the new attribute setting is created.

**Comment by nrichardson99** [comment]
@abrougher Appears this has been fixed at some point for transformers however a delimited parser has this issue.  I'll open a new issue for the parser as I'm not finding an existing issue for it.

**Comment by abrougher** [comment]
@nrichardson99 Can we close this one?

**Comment by nrichardson99** [comment]
Closing as it does appear to be working.
