### ISSUE TITLE
ORA-01747: invalid user.table.column, table.column, or column specification

### ISSUE THREAD

**Issue by spyhunter88** [JumpMind/metl#382]
When I write Model to Oracle database (11.2.0.1.0), when table has column named "USER", I can not Write to this table. I change to ACTOR or something else, it works.
I see the log print:
`
INSERT INTO IMPORT_LOG(USER, ACTION, DESCRIPTION) VALUE (?,?,?)
`
Please add double quote, backslash or square brackets depend on database.

**Comment by chenson42** [comment]
Have you tried to enable "Quote table and column names"?

**Comment by spyhunter88** [comment]
Sorry I don't read this config.

**Comment by chenson42** [comment]
No problem.  Let us know any other issues you run into!
