### ISSUE TITLE
Hint with alias name

### ISSUE THREAD

**Issue by spyhunter88** [JumpMind/metl#387]
Hi,

I have selected more than 20 columns in 4 tables with the same name. But they output to 4 Output Model. I want they output in the same Output Model.
With the hint function, I need to write 20 lines of code in 3 (keep first table) tables. Why I can't use alias name in SQL? The following code is in mysql, other database maybe difference.
`select col1, col2.... from my_table_data_2 as my_table_data_1;`

**Comment by nrichardson99** [comment]
You use hints on the column references themselves if you need the component to map to a different output model.  It won't pick up table aliases when mapping the output.

select col1 /* my_table_data_1.col1 */ 
     , col2 /* my_table_data_1.col2 */
     , col3 /* my_table_data_1.col3 */
     .... 
from my_table_data_2 ;

For another example see example 2 at https://github.com/JumpMind/metl/wiki/rdbms-reader

**Comment by spyhunter88** [comment]
Yes, I see this, my idea is just use alias as a 'short hand' when I have alot of columns, and they have the same names between tables. And I can also use `SELECT * FROM ` instead of defined which column is required.

**Comment by spyhunter88** [comment]
Also, please add note to User-Guide where to put comma when use hint. I usually use query like:
```
SELECT
    a, /* TABLE_MODEL.A_MODEL */
    b, /* TABLE_MODEL.B_MODEL */
    ...
FROM my_table
```

This code above can work, maybe can map but output results are wrong.
I waste time to understand the comma needs to be after the hint. Like below:
```
SELECT
    a /* TABLE_MODEL.A_MODEL */
    ,b /* TABLE_MODEL.B_MODEL */
    ,c /* TABLE_MODEL.C_MODEL */
    ...
FROM my_table
```

Thanks,

**Comment by nrichardson99** [comment]
Text added to the RDBMS Reader Wiki page: 'hints need to directly follow the field they correspond to prior to any comma if other fields follow the hint.'
