### ISSUE TITLE
Add table/grid export functionality to some of the metl component's UIs so interface documentation can be exported

### ISSUE THREAD

**Issue by chenson42** [JumpMind/metl#408]
Add table/grid export functionality to some of the metl component's UIs so interface documentation can be exported

**Comment by chenson42** [comment]
@abrougher Checked in an example for EditFormatPanel.  Is that what you were envisioning?

**Comment by abrougher** [comment]
Perfect.

**Comment by nrichardson99** [comment]
Reopen to include additional components to export.
