### ISSUE TITLE
Run view with the diagram should not show RED for cancelled steps.  That makes it hard to figure out which step failed.

### ISSUE THREAD

**Issue by chenson42** [JumpMind/metl#446]
Run view with the diagram should not show RED for cancelled steps.  That makes it hard to figure out which step failed.

**Comment by abrougher** [comment]
It's  a quick fix. Just need to determine a color. Should we use the blue that means it hasn't been run yet? Pink?

**Comment by abrougher** [comment]
Fixed: 852849f60a6b57b0733ab532eabbd7aa57cbd74f
