### ISSUE TITLE
Support reading common spreadsheet file formats.

### ISSUE THREAD

**Issue by abrougher** [JumpMind/metl#480]
I have a specific use case where I'd like to load 50 similar formatted spreadsheets.

**Comment by chenson42** [comment]
@gwilmer was playing around with an excel reader component yesterday ....

**Comment by gwilmer** [comment]
Austin, lets talk about your use case and see if the current implementation works for you.  Thanks!

**Comment by abrougher** [comment]
I wanted to use it for some one time conversions where spreadsheets were provided. Instead of converting each spreadsheet to a csv it will be easier to read directly from a spreadsheet. 

I believe this will work for future conversions. Thanks!
