### ISSUE TITLE
Content router target selection list not updated (and workaround)

### ISSUE THREAD

**Issue by john5000** [JumpMind/metl#482]
I have an existing content router and I've added I've added another destination component and drawn the connection to it on the gui.  

Problem area: I click the Component Editor of the content router and the Target Step drop down does not include my the component that I just added.   

No amount of clicking and re-selecting would make it show up. Seems there is no way to refresh to make it show. (then somehow later it showed up... happened several times.  Then I found the workaround.)

Workaround: close the tab for that Component Editor and re-open it.  Then the drop down list is updated.

Using: metl 1.3.1.r37

**Comment by chenson42** [comment]
I can recreate this.  I think several of our screens are like this.  Need to architect the component editors to receive refresh events.
