### ISSUE TITLE
File readers can fail to connect to a remote landing and still complete successfully.

### ISSUE THREAD

**Issue by abrougher** [JumpMind/metl#520]
When a file reader (BinaryFileReader, TextFileReader, or XmlReader) has the property 'Must Exist' set to false, we don't check to see why we the remote file couldn't be accessed. 

If a remote landing cannot be accessed due to networking or configuration issues, the component should fail regardless of the 'Must Exist' property being set.

**Comment by chenson42** [comment]
What resource were you using when you encountered this?

**Comment by abrougher** [comment]
Oh I see. The resource is responsible for throwing an exception.

We were use a TextFileReader with an SFTP resource.

The user we were using to connect to the landing was "locked out". We were unable to SFTP in.
