### ISSUE TITLE
The Http Response component will display illegible characters

### ISSUE THREAD

**Issue by xiaomeyu** [JumpMind/metl#554]
I use RDBMS Reader component to search data from Oracle DB(Charset UTF8).
Then I map the model from DB to Output Model and use Serializer and Http Response component to return the data.
It works well when I execute the SQL  in RDBMS Reader. ------------output string: MY15用户
But the Http Response will display illegible characters.  --------------output string: MY15????
------------------------------------Flows
Http Request ->RDBMS Reader->Mapping->Serializer->Http Response
![image](https://cloud.githubusercontent.com/assets/19358917/19374036/4f4b1df0-91fb-11e6-9064-07d93520e63e.png)

Thanks for your help!

**Comment by chenson42** [comment]
fyi - committed under the wrong issue.

**Comment by chenson42** [comment]
Where are you seeing MY15?????

Returning from the web service or in the input logging for http response?

**Comment by xiaomeyu** [comment]
It is returned from the web service.
----------
[{"name":"ServiceLog","data":{"date":"2016-10-08 10:00:00.0","title":"MY15????","id":"246118"}}]

**Comment by chenson42** [comment]
If you turn log input on in the 'Http Response 1' component do you see the correct values?  

If so, then at that point all the marshalling happens via Spring and Jetty.  You can try setting the -Dfile.encoding=utf-8 system property.  I would also make sure that your client is requesting the correct character set.

**Comment by xiaomeyu** [comment]
Thank you for your reply.
I had debugged the source code.
Then I found all the string's encoding is correct including the response.
But the explorer can not determine the content type.
I set a default value for response when the content type is null and fix the problem.
![image](https://cloud.githubusercontent.com/assets/19358917/19512433/7385ab50-961e-11e6-920a-076f260ba92c.png)

**Comment by chenson42** [comment]
Defaulting the content type to: application/octet-stream;charset=utf-8 if it isn't specified

**Comment by chenson42** [comment]
Also, auto set the content type when a serializer is used.
