### ISSUE TITLE
Delimited Parser: The order of the attributes in the parser is not set until the component is edited.

### ISSUE THREAD

**Issue by abrougher** [JumpMind/metl#565]
When the parser's model is selected, the order of attributes assigned to the model is not persisted in the db. 

When the flow is exported and imported into a different system, the order can be functionally different than it was on the source system.

**Comment by chenson42** [comment]
@abrougher I think this is fixed with the explicit ordering of model attributes.  Would you agree?

**Comment by abrougher** [comment]
I didn't realize they were ordered now. Agreed!

**Comment by chenson42** [comment]
They are as of a few minutes ago
