### ISSUE TITLE
METL can get into a situation where it cannot read from the execution database.

### ISSUE THREAD

**Issue by abrougher** [JumpMind/metl#569]
See stack trace below...

> 2016-10-26 13:13:51,351 ERROR [BackgroundRefresherService] [ui-refresher-1] Invocation of method valueChange in org.jumpmind.metl.ui.views.ManageView$2 failed.
> com.vaadin.event.ListenerMethod$MethodException: Invocation of method valueChange in org.jumpmind.metl.ui.views.ManageView$2 failed.
>     at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:531)
>     at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:198)
>     at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:161)
>     at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1008)
>     at com.vaadin.ui.AbstractField.fireValueChange(AbstractField.java:1163)
>     at com.vaadin.ui.AbstractField.setValue(AbstractField.java:570)
>     at com.vaadin.ui.AbstractSelect.setValue(AbstractSelect.java:735)
>     at com.vaadin.ui.AbstractField.setValue(AbstractField.java:468)
>     at com.vaadin.ui.AbstractSelect.setValue(AbstractSelect.java:697)
>     at org.jumpmind.metl.ui.views.ManageView.getBackgroundData(ManageView.java:276)
>     at org.jumpmind.metl.ui.views.ManageView.onBackgroundDataRefresh(ManageView.java:265)
>     at org.jumpmind.metl.ui.init.BackgroundRefresherService.refresh(BackgroundRefresherService.java:87)
>     at org.jumpmind.metl.ui.init.BackgroundRefresherService.lambda$setPollingInterval$0(BackgroundRefresherService.java:77)
>     at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
>     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
>     at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
>     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
>     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
>     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>     at java.lang.Thread.run(Thread.java:745)
> Caused by: com.vaadin.event.ListenerMethod$MethodException: Invocation of method valueChange in org.jumpmind.metl.ui.views.ManageView$2 failed.
>     at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:531)
>     at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:198)
>     at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:161)
>     at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1008)
>     at com.vaadin.ui.AbstractField.fireValueChange(AbstractField.java:1163)
>     at com.vaadin.ui.AbstractField.setValue(AbstractField.java:570)
>     at com.vaadin.ui.AbstractSelect.setValue(AbstractSelect.java:735)
>     at com.vaadin.ui.AbstractField.setValue(AbstractField.java:468)
>     at com.vaadin.ui.AbstractSelect.setValue(AbstractSelect.java:697)
>     at org.jumpmind.metl.ui.views.ManageView.getBackgroundData(ManageView.java:286)
>     at org.jumpmind.metl.ui.views.ManageView$2.valueChange(ManageView.java:136)
>     at sun.reflect.GeneratedMethodAccessor216.invoke(Unknown Source)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke(Method.java:497)
>     at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:508)
>     ... 20 more
> Caused by: org.jumpmind.db.sql.SqlException: Failed to execute sql: select id, agent_id, flow_id, deployment_id, deployment_name, agent_name, host_name, flow_name, status, start_time, end_time, create_by, last_update_by, parameters from METL_execution where status = ? order by create_time desc limit 100
>     at org.jumpmind.db.sql.AbstractSqlTemplate.translate(AbstractSqlTemplate.java:283)
>     at org.jumpmind.db.sql.JdbcSqlReadCursor.<init>(JdbcSqlReadCursor.java:108)
>     at org.jumpmind.db.sql.JdbcSqlTemplate.queryForCursor(JdbcSqlTemplate.java:134)
>     at org.jumpmind.db.sql.AbstractSqlTemplate.query(AbstractSqlTemplate.java:182)
>     at org.jumpmind.db.sql.AbstractSqlTemplate.query(AbstractSqlTemplate.java:177)
>     at org.jumpmind.db.sql.AbstractSqlTemplate.query(AbstractSqlTemplate.java:118)
>     at org.jumpmind.metl.core.persist.ExecutionSqlService.findExecutions(ExecutionSqlService.java:91)
>     at sun.reflect.GeneratedMethodAccessor329.invoke(Unknown Source)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke(Method.java:497)
>     at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
>     at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
>     at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
>     at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:133)
>     at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:121)
>     at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
>     at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:208)
>     at com.sun.proxy.$Proxy34.findExecutions(Unknown Source)
>     at org.jumpmind.metl.ui.views.ManageView.getBackgroundData(ManageView.java:311)
>     at org.jumpmind.metl.ui.views.ManageView$2.valueChange(ManageView.java:136)
>     at sun.reflect.GeneratedMethodAccessor216.invoke(Unknown Source)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke(Method.java:497)
>     at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:508)
>     ... 34 more
> Caused by: org.h2.jdbc.JdbcSQLException: General error: "java.lang.IllegalStateException: Reading from cache:nio:/data/metl/metl_db/exec_db/metl-exec.db.mv.db failed; file length -1 read length 768 at 6873373 [1.4.191/1]"; SQL statement:
> select id, agent_id, flow_id, deployment_id, deployment_name, agent_name, host_name, flow_name, status, start_time, end_time, create_by, last_update_by, parameters from METL_execution where status = ? order by create_time desc limit 100 [50000-191]
>     at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
>     at org.h2.message.DbException.get(DbException.java:168)
>     at org.h2.message.DbException.convert(DbException.java:295)
>     at org.h2.command.Command.executeQuery(Command.java:213)
>     at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:110)
>     at org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
>     at org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
>     at org.jumpmind.db.sql.JdbcSqlReadCursor.<init>(JdbcSqlReadCursor.java:85)
>     ... 56 more
> Caused by: java.lang.IllegalStateException: Reading from cache:nio:/data/metl/metl_db/exec_db/metl-exec.db.mv.db failed; file length -1 read length 768 at 6873373 [1.4.191/1]
>     at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:773)
>     at org.h2.mvstore.DataUtils.readFully(DataUtils.java:443)
>     at org.h2.mvstore.FileStore.readFully(FileStore.java:98)
>     at org.h2.mvstore.Page.read(Page.java:190)
>     at org.h2.mvstore.MVStore.readPage(MVStore.java:1939)
>     at org.h2.mvstore.MVMap.readPage(MVMap.java:736)
>     at org.h2.mvstore.Page.getChildPage(Page.java:217)
>     at org.h2.mvstore.Cursor.min(Cursor.java:129)
>     at org.h2.mvstore.Cursor.hasNext(Cursor.java:36)
>     at org.h2.mvstore.db.TransactionStore$TransactionMap$1.fetchNext(TransactionStore.java:1384)
>     at org.h2.mvstore.db.TransactionStore$TransactionMap$1.<init>(TransactionStore.java:1380)
>     at org.h2.mvstore.db.TransactionStore$TransactionMap.keyIterator(TransactionStore.java:1375)
>     at org.h2.mvstore.db.TransactionStore$TransactionMap.keyIterator(TransactionStore.java:1363)
>     at org.h2.mvstore.db.MVSecondaryIndex.find(MVSecondaryIndex.java:308)
>     at org.h2.mvstore.db.MVSecondaryIndex.find(MVSecondaryIndex.java:253)
>     at org.h2.index.BaseIndex.find(BaseIndex.java:132)
>     at org.h2.index.IndexCursor.find(IndexCursor.java:169)
>     at org.h2.table.TableFilter.next(TableFilter.java:460)
>     at org.h2.command.dml.Select.queryFlat(Select.java:541)
>     at org.h2.command.dml.Select.queryWithoutCache(Select.java:654)
>     at org.h2.command.dml.Query.query(Query.java:341)
>     at org.h2.command.dml.Query.query(Query.java:309)
>     at org.h2.command.dml.Query.query(Query.java:36)
>     at org.h2.command.CommandContainer.query(CommandContainer.java:110)
>     at org.h2.command.Command.executeQuery(Command.java:201)
>     ... 60 more
> Caused by: java.nio.channels.ClosedChannelException
>     at sun.nio.ch.FileChannelImpl.ensureOpen(FileChannelImpl.java:110)
>     at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:720)
>     at org.h2.store.fs.FileNio.read(FilePathNio.java:74)
>     at org.h2.mvstore.cache.FilePathCache$FileCache.read(FilePathCache.java:87)
>     at org.h2.mvstore.DataUtils.readFully(DataUtils.java:429)
>     ... 83 more

**Comment by chenson42** [comment]
Sounds like this might be caused by this:  https://github.com/h2database/h2database/issues/227

**Comment by chenson42** [comment]
I think this setting is causing intermittent h2 startup issues in my dev environment

**Comment by chenson42** [comment]
[Reproduce.java.zip](https://github.com/JumpMind/metl/files/760927/Reproduce.java.zip)

**Comment by chenson42** [comment]
If you start and access H2 in server mode this isn't an issue.  Going that route.
