### ISSUE TITLE
SMTP Component

### ISSUE THREAD

**Issue by abrougher** [JumpMind/metl#58]
Create a component for sending emails.

Email messages involve multiple fields; to, from, subject, attachment, body. It might make sense to pass in text or entities to this component. Text option would allow the use of a formatter on the body text while an entity input would allow more programmatic control of the fields the email is sent to.  If an entity is the input, you could specify an attribute for each field in the email. If text is the input, you would need to use parameters or scripting to define fields other than the body text.

**Comment by chenson42** [comment]
This was done in 1.5!
