### ISSUE TITLE
Explore DataSource Screen: Hide other user agent db resources.

### ISSUE THREAD

**Issue by abrougher** [JumpMind/metl#609]
Metl currently displays each user agents resources. 

We should hide other user agents.

**Comment by chenson42** [comment]
I added a new field to the Database Resource called: "Show On Explore Screen".  If this is set then the explore screen will show a resource with the default settings from the design view.  It will be named "Design {Resource Name}"

I also added a check box to the edit agent screen that is "Explore?" with a description of "Show resources deployed to this agent in the explore view".  If this is set, then all the database resources for the agent are shown in the database explore screen.
