### ISSUE TITLE
Cannot view previously run flow for more than 1 second.

### ISSUE THREAD

**Issue by abrougher** [JumpMind/metl#669]
Metl Version: version 2.0.0.m.1500

To recreate:

- Select Manage Tab
- Select Design Time Agent
- Double click flow in the "Executions" screen.
- Try to view the previous flow run for more than a second.

**Comment by chenson42** [comment]
I could not reproduce this.  Is this only when running from a war file?

**Comment by abrougher** [comment]
I can't recreated it anymore either. I had tried it with several flows, and even tried restarting my browser. Closing as I cannot recreate. (I was using a war file)
