### ISSUE TITLE
Not able to import model structure from non-metl databases

### ISSUE THREAD

**Issue by abismail** [JumpMind/metl#726]
so I'm on Ubuntu 17.04 and I'm writing this HUGE flow, which requires 10 tables of up to maybe 30 fields each, but after adding a new database resource, I don't find that database in the import dialog:
![metl0](https://cloud.githubusercontent.com/assets/671091/26491955/17f5d436-4212-11e7-854c-63627f0f1254.png)

![metl1](https://cloud.githubusercontent.com/assets/671091/26491971/2d4f5e2e-4212-11e7-9098-a9e49ce15bf6.png)

if you guys are doing a lookup on the databases that are configured to be used then this should be easy to fix. Unless you guys are only looking in the databases kept inside the metl instance. (That would be bad, unless the import function is for a different purpose)

Can I fix this myself? if so: where would I find this code?
Thanks!

**Comment by abrougher** [comment]
It looks like there was a recent code change made to restrict displaying too many database resources on the explorer screen. Unfortunately, it also made the database table import dialog confusing.

When an agent is marked for "explore", all of the resources become available on the explore panel and the DB Import dialog. This is useful when a Metl instance has a lot of agents.

To mark an agent to explore:

1) Open the deploy tab
2) Open your design time agent (or any other agent with the db resource)
3) Check the "Explore?" checkbox.

![image](https://cloud.githubusercontent.com/assets/6471686/26516910/68dd3d22-425c-11e7-84b0-b9420958a2c1.png)

You should be able to go back into the model import dialog and select your database.

I created a separate enhancement request to make this functionality less confusing.

The Model DB Import dialog does not show all project resources by default.  #727

Thanks for pointing this out!
