### ISSUE TITLE
How to fix zeroed Timestamp?

### ISSUE THREAD

**Issue by abismail** [JumpMind/metl#733]
Hi guys,

I know I'm posting here A LOT but this is the only place I'm getting any help at. And I appreciate all the help so far.

Okay so down to my problem;
- I have a datasource that has tables with fields (created and updated, etc.) that are date timestamps with their values zeroed: '0000-00-00 00:00:00' 
- When I try and read from this data source I get a SQLException: Value '0000-00-00 00:00:00' can not be represented as java.sql.Timestamp.
- After updating the model to read the value in as VARCHAR I still get the same error!!! (?_?)

I suspect it's got something to do with the flow using a model that's already loaded into memory/cache, but how do I update it?

**Comment by abrougher** [comment]
Try casting the date timestamp to a varchar in the query.

When you cast the column you'll need to make sure you add a hint so Metl knows how to map the result of the cast.

e.g.
select
cast(my_date as varchar) /* foo.my_date */ 
from foo;

Please close the issue if this works.

**Comment by abrougher** [comment]
Hi @abismail, were you able to test the suggestion above? Can you close if this worked?
