### ISSUE TITLE
Format Delimited: columns always trimmed, not needed

### ISSUE THREAD

**Issue by devneri** [JumpMind/metl#739]
When data (not trimmed) comes from RDBMS Reader, the "Format Delimited" component doesn't format correctly to "Text File Writer" component, trimming all dataset columns indistinctly.

How can get through this? I would like the component do not trim if not requested.

I've already let unchecked the "Trim Columns" option on RDBMS Reader without solution.

**Comment by abrougher** [comment]
Hi @devneri 
The delimited formatter is trimming values by default when writing to a delimited format. 

I created a git hub issues to expose an option to turn this behavior on and off via a property.

Delimited Formatter: Add a property to configure whether delimited values are trimmed. #763

I'm going to close this issue, please follow issue #763
