### ISSUE TITLE
Need help importing repo into eclipse

### ISSUE THREAD

**Issue by abismail** [JumpMind/metl#742]
Hi guys,

This is URGENT; I need to read data from Google Analytics, but Google Analytics' API only supports OAuth 2.0 right now and have deprecated OAuth1.0 in 2015, so I want to add OAuth 2.0 support, but I'm having trouble importing the project into Eclipse and running it from there.

Things to note:
I've installed Gradle projects plugin, e2m / maven plugin and eclipse Marketplace so far.
Whenever I do load the project into eclipse I get multiple errors where eclipse says to resolve by using JRE 1.5. but that can't be right... right?

So my main question is: What method do I use to import your project into eclipse so I can add functionality?

We will not be using metl if we cannot connect to Google Analytics. And the decision whether or not to keep it is to be finalized this week. So please Help me out here guys!

If I can get this 1 issue fixed, I'm sure I'll no longer have to come and siff through / create issues to move forward

**Comment by chenson42** [comment]
Check the projects out of git and then cd into the metl-assemble directory and run:
`./gradlew develop`

You should only have to refresh you eclipse projects and everything should be ready to go.

Note, you do need JDK 8 installed ...

**Comment by abismail** [comment]
okay, so I've run ./gradlew assemble in `metl-assemble` and I've installed jdk 8 but I can't tell eclipse to build using jdk 8 even after a restart. I guess at this point it's an IDE issue, simply refreshing the project doesn't do the trick.

I'll find some help on StackOverflow in the mean time.

**Comment by abrougher** [comment]
Hi @abismail, can we close this issue since you've narrowed it down to the IDE?
