### ISSUE TITLE
Add Project Level Filtering

### ISSUE THREAD

**Issue by abrougher** [JumpMind/metl#771]
Users should have the option to filter which projects are displayed in their work space.

Implementation: 

Today the design screen menu has File and Edit options. We should add a View option.

Under the View menu will be two additional options.
View
    Filter Projects
    Manage Filter

When Filter Projects is clicked, the user setting "design.navigator.filter.enabled" will be updated (true/false) indicating that only the projects they have selected to be displayed are displayed. The menu drop down should display a check mark next to "Filter Projects" option indicating that the option has been selected.

When the user clicks "Manager Filter", a dialog will be displayed with a list of projects. The user can then select which projects should be added to their filtered view.

As a user selects or unselects projects from their view, their preferences will automatically be saved in the METL_USER_SETTING table. Each user would have a single setting, "design.navigator.filter.projects", with a comma delimited list of project guids. 

Eventually we would like to add project level permissions in addition to filtering but this is a separate task.

**Comment by gwilmer** [comment]
Closing with Tags implementation
