### ISSUE TITLE
Mail sending issue

### ISSUE THREAD

**Issue by devneri** [JumpMind/metl#774]
I've an issue using mail notifications. This is the mail server configuration:

![image](https://user-images.githubusercontent.com/9848369/30670252-e7ed0de8-9e61-11e7-8627-20397be270c4.png)

SMTP Test connection is ok, but when a notification is triggered, the mail is blocked by (in this case) SendGrid with this message:

![image](https://user-images.githubusercontent.com/9848369/30670105-5906ec8e-9e61-11e7-863b-e10eee3c3d61.png)

**Comment by abrougher** [comment]
Hi @devneri,

Thanks again for the contribution. Can we close this issue?

Thanks

**Comment by devneri** [comment]
Yes, perfect! Thank you!
