### ISSUE TITLE
RDBMS Reader: allow duplicate hints if hint only contains entity

### ISSUE THREAD

**Issue by kranskydog** [JumpMind/metl#783]
If I have query
          `select a.column1 /*entityx*/,`
          `a.column2 /*entityy*/,`
          `b.column3 /*entityx*/,`
          `c.column4 /*entityy*/`
          `from table1 a, table2 b, table3 c`
          `where.....`
it will not allow the duplication of the hint, even though they actually end up being distinct entity.attribute values

**Comment by gwilmer** [comment]
Just to make sure I understand what you are looking for....  You want:

a.column1 ==> entityx.column1
b.column3 ==> entityx.column3
a.column2 ==> entityy.column2
c.column4 ==> entityy.column4

Is that correct?

Thanks,
Greg w.

**Comment by kranskydog** [comment]
Hi Greg
Yes, that's correct.
Note, lines 186-191 in RdbmsReader.java applies it correctly, its just that getSqlColumnEntityHints doesn't permit duplicates on the assumption every hint is 'entity.attribute' 
Phil.

**Comment by abrougher** [comment]
Hi @kranskydog 

Take a look at the unit test in RdbmsReaderTest to make sure this addresses your issue.
https://github.com/JumpMind/metl/blob/fe3fd3e066b6ba87ffeb9295cc3a735bfd7bbffb/comp-rdbms-reader/src/test/java/org/jumpmind/metl/core/runtime/component/RdbmsReaderTest.java#L48

Thanks
