### ISSUE TITLE
Admin screens 'General Settings' and 'Edit Notifications' need vertical scroll bars

### ISSUE THREAD

**Issue by kranskydog** [JumpMind/metl#799]
On smaller screens (laptop) they dont fit in the screen, and there is no way to see top/bottom of the screen unless you use tab/shift-tab to navigate the screen

![image](https://user-images.githubusercontent.com/32562685/33194898-598a3afa-d127-11e7-9fb0-7400d4a960fd.png)

![image](https://user-images.githubusercontent.com/32562685/33194914-6e617dee-d127-11e7-838b-612e861d6025.png)

**Comment by abrougher** [comment]
@kranskydog , I see the issue on the General Settings page but I was unable to recreate the scroll bar issue on the Notification edit screen. Both firefox and chrome worked correctly.

I can see all the fields in your screenshot. Can you make your window a little bit smaller and see if the scroll bar shows up?

![image](https://user-images.githubusercontent.com/6471686/33390664-9579d760-d504-11e7-9f6f-ff00b874be85.png)

**Comment by abrougher** [comment]
Same issue exists on the Mail Server panel.
