### ISSUE TITLE
Merge-Components - Hints to output-datamodell are working not properly

### ISSUE THREAD

**Issue by stefanhenz** [JumpMind/metl#861]
Hi

We really appreciate working with your tool. It's safed us al lot scripting work. But now we have some special effects that if we merge different datasources in a the temp-db component that some hints are not filled with data. The elements, to which we refer, are correctly inserted in the data-modell and can be used in the next-components. But the temp-db component is not passing/filling in the information. 

Even a test with very basic static strings or integer values will not be passed on.

If you need any further information for debugging we can provide you our example flows.

Best regards 

Stefan

**Comment by stefanhenz** [comment]
Hi Greg, 

as I explained in the last post here the examples. May be it's a silly mistake but my work mate an I double checked it serveral times. 


[flow-config-20180730211023.zip](https://github.com/JumpMind/metl/files/2242558/flow-config-20180730211023.zip)

The result will look like this:
`OUTPUT Message Payload: {"ChangeType" : "ADD"
"access_requests.room_id" : 32, 
"access_requests.status" : "allowed", 
"access_requests.notes" : "This is a message", 
"access_requests.requester_id" : 89}`

The related query like this: 
`select 
ro.id /* access_requests.room_id */ 
, re.status /* access_requests.status */
, re.notes /* access_requests.notes */
, pe.id /* access_requests.requester_id */
, case when (select id from Person where Person.iet_contact_id = re.iet_grantor_id) then (select id from Person where Person.iet_contact_id = re.iet_grantor_id) ELSE 1 END  /* access_requests.grantor_id */
, re.access_dt  /* access_requests.access_from */
, re.access_end_dt  /* access_requests.access_to */
 from AccessRequest_iet as re, Person as pe, Room as ro
where pe.iet_contact_id = re.iet_requester_id and ro.iet_room_id = re.iet_room_id`

The field grantor will be empty all the time. It makes no difference if we use our query or any static value. 

Thanks for help

Best regards

Stefan H.

**Comment by abrougher** [comment]
Hi Stefan,

This is probably a little late but it may help someone else. 

This is a known issue with the the SQL hint parser. It gets hung up on the embedded select statements. 

There is a work around that can be found here...
https://github.com/JumpMind/metl/issues/846#issuecomment-401848679

I'm going to close this as a duplicate for now. Thanks
