### ISSUE TITLE
where the login move to？

### ISSUE THREAD

**Issue by dong0501** [JumpMind/metl#865]
Release,Login, User,Group ,Notification... 
Why remove their code from metl?

**Comment by erilong** [comment]
We're preparing to release a commercial version of Metl, and some features that are geared towards business were moved to that private version.  Hopefully we can find a balance between open core and a version that can fund future development.  We'll continue to add new features to the open source version and may bring back the features you listed once the commercial version gains a foothold.  You can always fork the previous version and continue to use those features too.

**Comment by dong0501** [comment]
ok
