### ISSUE TITLE
METL stand alone install is failing and hangs if no "conf" directory is present.

### ISSUE THREAD

**Issue by abrougher** [JumpMind/metl#871]
Release Version: 3.2.2.r.83

When running stand alone (java -jar metl.jar) the install hangs if there is no "conf" folder pre-created. Metl should create the conf folder and create the metl.properties file itself if one does not exist.

When metl hangs there are no helpful messages at the std out or in a log file. The only folders created are plugins, and security.

> Metl can be reached on http://0.0.0.0:42000/metl
> Metl can be reached on https://0.0.0.0:42443/metl
> 
> Version: 3.2.2.r.83
> Could not find the /Users/austin/Downloads/conf/metl.properties configuration file.  A default version will be written.

If I create the conf folder myself, Metl will start up fine. This doesn't seem to be a permissions issue because I can create the folder myself with the same user.

**Comment by erilong** [comment]
This should be fixed on the master branch.

**Comment by abrougher** [comment]
> This should be fixed on the master branch.

I'll see if I can find the commit and cherry pick it. Thanks!

**Comment by erilong** [comment]
I think the fix is in AppUtils and AppInitializer.  Sorry for the trouble.
