### ISSUE TITLE
Gateway components appear to run when missing the control link.

### ISSUE THREAD

**Issue by abrougher** [JumpMind/metl#938]
The gateway component requires the 'Gate Control Source' property be set. This value can be set once a link is created to a control source. 

An issue arrises if the link to the control source is deleted (on purpose or accident). The flow runtime will validate that the required field is set but it should also validate that a link exists to that control source.

If the link is missing, the flow should never start.

**Comment by nrichardson99** [comment]
@abrougher I am not able to recreate this on 3.5.1.  What version do you see this on?

**Comment by abrougher** [comment]
3.3.0.r6

When you recreate, can you try deleting the link and running it? 

What happens if the link is there but you have not unset the source?

**Comment by nrichardson99** [comment]
I've tried not adding a link, adding a link and removing it, copying the component and removing the link.  All Failed the flow.
When I re-add a previously linked control source the drop-down auto fills with that last selected value.  
I believe the version you are running is prior to your change.

**Comment by abrougher** [comment]
OK, thanks for testing! Closing the issue since it cannot be recreated.
