### ISSUE TITLE
Deploy option not available

### ISSUE THREAD

**Issue by shankaryadavy9** [JumpMind/metl#948]
Hi Team,

I can see deploy option in  documentation but not available in a war I am running. I am running latest version Metl. And not able to add users too.
Am I missing something.

**Comment by ankitravan** [comment]
Hi Team,

I facing the same issue like want to create a user. But under the Admin Navigation User option is not available.

I have attached Screens for your reference and below the URL where I have downloaded the war file.

URL: https://github.com/JumpMind/metl


![Admin Navigation](https://user-images.githubusercontent.com/53144540/88632050-b7952000-d0d0-11ea-94d5-e7e11fa40ede.PNG)
![MetlDownloadScreen](https://user-images.githubusercontent.com/53144540/88632055-b8c64d00-d0d0-11ea-829e-3fda18fb1d13.PNG)

**Comment by nrichardson99** [comment]
A while back, the application was separated into open source and commercial.  The open source has core data integration features, but enterprise features like multiple users and scheduling were moved to the commercial version.
Sorry about the confusion with the documentation we didn't realize that hadn't been updated.
